//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 03:41:53 PM IST 
//


package gov.shdrc.webservice.reader;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shrdcpa" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="First_Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shrdccl" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Final_App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shrdcdccl" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Diagnostic_Center" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Final_App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shrdcpayment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PayerZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TDS" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="OtherDeduction" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="NetPayable" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="PaymentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ClaimProcessTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EftCreationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PaymentConfirmTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shrdchosp" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HOSPCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HOSPNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LOCATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OWNERTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shrdcpa",
    "shrdccl",
    "shrdcdccl",
    "shrdcpayment",
    "shrdchosp"
})
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

    protected List<NewDataSet.Shrdcpa> shrdcpa;
    protected List<NewDataSet.Shrdccl> shrdccl;
    protected List<NewDataSet.Shrdcdccl> shrdcdccl;
    protected List<NewDataSet.Shrdcpayment> shrdcpayment;
    protected List<NewDataSet.Shrdchosp> shrdchosp;

    /**
     * Gets the value of the shrdcpa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shrdcpa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShrdcpa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewDataSet.Shrdcpa }
     * 
     * 
     */
    public List<NewDataSet.Shrdcpa> getShrdcpa() {
        if (shrdcpa == null) {
            shrdcpa = new ArrayList<NewDataSet.Shrdcpa>();
        }
        return this.shrdcpa;
    }

    /**
     * Gets the value of the shrdccl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shrdccl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShrdccl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewDataSet.Shrdccl }
     * 
     * 
     */
    public List<NewDataSet.Shrdccl> getShrdccl() {
        if (shrdccl == null) {
            shrdccl = new ArrayList<NewDataSet.Shrdccl>();
        }
        return this.shrdccl;
    }

    /**
     * Gets the value of the shrdcdccl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shrdcdccl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShrdcdccl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewDataSet.Shrdcdccl }
     * 
     * 
     */
    public List<NewDataSet.Shrdcdccl> getShrdcdccl() {
        if (shrdcdccl == null) {
            shrdcdccl = new ArrayList<NewDataSet.Shrdcdccl>();
        }
        return this.shrdcdccl;
    }

    /**
     * Gets the value of the shrdcpayment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shrdcpayment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShrdcpayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewDataSet.Shrdcpayment }
     * 
     * 
     */
    public List<NewDataSet.Shrdcpayment> getShrdcpayment() {
        if (shrdcpayment == null) {
            shrdcpayment = new ArrayList<NewDataSet.Shrdcpayment>();
        }
        return this.shrdcpayment;
    }

    /**
     * Gets the value of the shrdchosp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shrdchosp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShrdchosp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewDataSet.Shrdchosp }
     * 
     * 
     */
    public List<NewDataSet.Shrdchosp> getShrdchosp() {
        if (shrdchosp == null) {
            shrdchosp = new ArrayList<NewDataSet.Shrdchosp>();
        }
        return this.shrdchosp;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Final_App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refno",
        "patientName",
        "gender",
        "patientAge",
        "payerZone",
        "hospital",
        "hospCode",
        "city",
        "memberCaste",
        "cardNo",
        "patientTPAID",
        "submissionTime",
        "authorizedTime",
        "tat",
        "status",
        "procedureName",
        "finalAppAmt",
        "remarks"
    })
    public static class Shrdccl {

        @XmlElement(name = "Refno", required = true)
        protected String refno;
        @XmlElement(name = "Patient_Name", required = true)
        protected String patientName;
        @XmlElement(name = "Gender", required = true)
        protected String gender;
        @XmlElement(name = "Patient_Age", required = true)
        protected String patientAge;
        @XmlElement(name = "Payer_Zone", required = true)
        protected String payerZone;
        @XmlElement(name = "Hospital", required = true)
        protected String hospital;
        @XmlElement(name = "HospCode", required = true)
        protected String hospCode;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "Member_Caste", required = true)
        protected String memberCaste;
        @XmlElement(name = "Card_No", required = true)
        protected String cardNo;
        @XmlElement(name = "Patient_TPA_ID", required = true)
        protected String patientTPAID;
        @XmlElement(name = "Submission_Time", required = true)
        protected String submissionTime;
        @XmlElement(name = "Authorized_Time", required = true)
        protected String authorizedTime;
        @XmlElement(name = "TAT", required = true)
        protected String tat;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Procedure_Name", required = true)
        protected String procedureName;
        @XmlElement(name = "Final_App_Amt")
        protected float finalAppAmt;
        @XmlElement(name = "REMARKS", required = true)
        protected String remarks;

        /**
         * Gets the value of the refno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefno() {
            return refno;
        }

        /**
         * Sets the value of the refno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefno(String value) {
            this.refno = value;
        }

        /**
         * Gets the value of the patientName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientName() {
            return patientName;
        }

        /**
         * Sets the value of the patientName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientName(String value) {
            this.patientName = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the patientAge property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientAge() {
            return patientAge;
        }

        /**
         * Sets the value of the patientAge property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientAge(String value) {
            this.patientAge = value;
        }

        /**
         * Gets the value of the payerZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerZone() {
            return payerZone;
        }

        /**
         * Sets the value of the payerZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerZone(String value) {
            this.payerZone = value;
        }

        /**
         * Gets the value of the hospital property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospital() {
            return hospital;
        }

        /**
         * Sets the value of the hospital property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospital(String value) {
            this.hospital = value;
        }

        /**
         * Gets the value of the hospCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospCode() {
            return hospCode;
        }

        /**
         * Sets the value of the hospCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospCode(String value) {
            this.hospCode = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the memberCaste property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberCaste() {
            return memberCaste;
        }

        /**
         * Sets the value of the memberCaste property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberCaste(String value) {
            this.memberCaste = value;
        }

        /**
         * Gets the value of the cardNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardNo() {
            return cardNo;
        }

        /**
         * Sets the value of the cardNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardNo(String value) {
            this.cardNo = value;
        }

        /**
         * Gets the value of the patientTPAID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientTPAID() {
            return patientTPAID;
        }

        /**
         * Sets the value of the patientTPAID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientTPAID(String value) {
            this.patientTPAID = value;
        }

        /**
         * Gets the value of the submissionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmissionTime() {
            return submissionTime;
        }

        /**
         * Sets the value of the submissionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmissionTime(String value) {
            this.submissionTime = value;
        }

        /**
         * Gets the value of the authorizedTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizedTime() {
            return authorizedTime;
        }

        /**
         * Sets the value of the authorizedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizedTime(String value) {
            this.authorizedTime = value;
        }

        /**
         * Gets the value of the tat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAT() {
            return tat;
        }

        /**
         * Sets the value of the tat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAT(String value) {
            this.tat = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the procedureName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcedureName() {
            return procedureName;
        }

        /**
         * Sets the value of the procedureName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcedureName(String value) {
            this.procedureName = value;
        }

        /**
         * Gets the value of the finalAppAmt property.
         * 
         */
        public float getFinalAppAmt() {
            return finalAppAmt;
        }

        /**
         * Sets the value of the finalAppAmt property.
         * 
         */
        public void setFinalAppAmt(float value) {
            this.finalAppAmt = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREMARKS() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREMARKS(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Diagnostic_Center" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Final_App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refno",
        "patientName",
        "gender",
        "patientAge",
        "payerZone",
        "hospCode",
        "diagnosticCenter",
        "city",
        "memberCaste",
        "cardNo",
        "patientTPAID",
        "submissionTime",
        "authorizedTime",
        "tat",
        "status",
        "procedureName",
        "finalAppAmt",
        "remarks"
    })
    public static class Shrdcdccl {

        @XmlElement(name = "Refno", required = true)
        protected String refno;
        @XmlElement(name = "Patient_Name", required = true)
        protected String patientName;
        @XmlElement(name = "Gender", required = true)
        protected String gender;
        @XmlElement(name = "Patient_Age", required = true)
        protected String patientAge;
        @XmlElement(name = "Payer_Zone", required = true)
        protected String payerZone;
        @XmlElement(name = "HospCode", required = true)
        protected String hospCode;
        @XmlElement(name = "Diagnostic_Center", required = true)
        protected String diagnosticCenter;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "Member_Caste", required = true)
        protected String memberCaste;
        @XmlElement(name = "Card_No", required = true)
        protected String cardNo;
        @XmlElement(name = "Patient_TPA_ID", required = true)
        protected String patientTPAID;
        @XmlElement(name = "Submission_Time", required = true)
        protected String submissionTime;
        @XmlElement(name = "Authorized_Time", required = true)
        protected String authorizedTime;
        @XmlElement(name = "TAT", required = true)
        protected String tat;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Procedure_Name", required = true)
        protected String procedureName;
        @XmlElement(name = "Final_App_Amt")
        protected float finalAppAmt;
        @XmlElement(name = "REMARKS", required = true)
        protected String remarks;

        /**
         * Gets the value of the refno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefno() {
            return refno;
        }

        /**
         * Sets the value of the refno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefno(String value) {
            this.refno = value;
        }

        /**
         * Gets the value of the patientName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientName() {
            return patientName;
        }

        /**
         * Sets the value of the patientName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientName(String value) {
            this.patientName = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the patientAge property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientAge() {
            return patientAge;
        }

        /**
         * Sets the value of the patientAge property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientAge(String value) {
            this.patientAge = value;
        }

        /**
         * Gets the value of the payerZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerZone() {
            return payerZone;
        }

        /**
         * Sets the value of the payerZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerZone(String value) {
            this.payerZone = value;
        }

        /**
         * Gets the value of the hospCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospCode() {
            return hospCode;
        }

        /**
         * Sets the value of the hospCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospCode(String value) {
            this.hospCode = value;
        }

        /**
         * Gets the value of the diagnosticCenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDiagnosticCenter() {
            return diagnosticCenter;
        }

        /**
         * Sets the value of the diagnosticCenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDiagnosticCenter(String value) {
            this.diagnosticCenter = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the memberCaste property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberCaste() {
            return memberCaste;
        }

        /**
         * Sets the value of the memberCaste property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberCaste(String value) {
            this.memberCaste = value;
        }

        /**
         * Gets the value of the cardNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardNo() {
            return cardNo;
        }

        /**
         * Sets the value of the cardNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardNo(String value) {
            this.cardNo = value;
        }

        /**
         * Gets the value of the patientTPAID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientTPAID() {
            return patientTPAID;
        }

        /**
         * Sets the value of the patientTPAID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientTPAID(String value) {
            this.patientTPAID = value;
        }

        /**
         * Gets the value of the submissionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmissionTime() {
            return submissionTime;
        }

        /**
         * Sets the value of the submissionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmissionTime(String value) {
            this.submissionTime = value;
        }

        /**
         * Gets the value of the authorizedTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizedTime() {
            return authorizedTime;
        }

        /**
         * Sets the value of the authorizedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizedTime(String value) {
            this.authorizedTime = value;
        }

        /**
         * Gets the value of the tat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAT() {
            return tat;
        }

        /**
         * Sets the value of the tat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAT(String value) {
            this.tat = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the procedureName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcedureName() {
            return procedureName;
        }

        /**
         * Sets the value of the procedureName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcedureName(String value) {
            this.procedureName = value;
        }

        /**
         * Gets the value of the finalAppAmt property.
         * 
         */
        public float getFinalAppAmt() {
            return finalAppAmt;
        }

        /**
         * Sets the value of the finalAppAmt property.
         * 
         */
        public void setFinalAppAmt(float value) {
            this.finalAppAmt = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREMARKS() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREMARKS(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HOSPCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HOSPNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LOCATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OWNERTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hospcode",
        "hospname",
        "location",
        "ownertype"
    })
    public static class Shrdchosp {

        @XmlElement(name = "HOSPCODE", required = true)
        protected String hospcode;
        @XmlElement(name = "HOSPNAME", required = true)
        protected String hospname;
        @XmlElement(name = "LOCATION", required = true)
        protected String location;
        @XmlElement(name = "OWNERTYPE", required = true)
        protected String ownertype;

        /**
         * Gets the value of the hospcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHOSPCODE() {
            return hospcode;
        }

        /**
         * Sets the value of the hospcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHOSPCODE(String value) {
            this.hospcode = value;
        }

        /**
         * Gets the value of the hospname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHOSPNAME() {
            return hospname;
        }

        /**
         * Sets the value of the hospname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHOSPNAME(String value) {
            this.hospname = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLOCATION() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLOCATION(String value) {
            this.location = value;
        }

        /**
         * Gets the value of the ownertype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOWNERTYPE() {
            return ownertype;
        }

        /**
         * Sets the value of the ownertype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOWNERTYPE(String value) {
            this.ownertype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Refno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Payer_Zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Member_Caste" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Card_No" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patient_TPA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="First_Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Submission_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Authorized_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Procedure_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="App_Amt" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="REMARKS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refno",
        "patientName",
        "gender",
        "patientAge",
        "payerZone",
        "hospital",
        "hospCode",
        "city",
        "memberCaste",
        "cardNo",
        "patientTPAID",
        "firstSubmissionTime",
        "submissionTime",
        "authorizedTime",
        "tat",
        "status",
        "procedureName",
        "appAmt",
        "remarks"
    })
    public static class Shrdcpa {

        @XmlElement(name = "Refno", required = true)
        protected String refno;
        @XmlElement(name = "Patient_Name", required = true)
        protected String patientName;
        @XmlElement(name = "Gender", required = true)
        protected String gender;
        @XmlElement(name = "Patient_Age", required = true)
        protected String patientAge;
        @XmlElement(name = "Payer_Zone", required = true)
        protected String payerZone;
        @XmlElement(name = "Hospital", required = true)
        protected String hospital;
        @XmlElement(name = "HospCode", required = true)
        protected String hospCode;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "Member_Caste", required = true)
        protected String memberCaste;
        @XmlElement(name = "Card_No", required = true)
        protected String cardNo;
        @XmlElement(name = "Patient_TPA_ID", required = true)
        protected String patientTPAID;
        @XmlElement(name = "First_Submission_Time", required = true)
        protected String firstSubmissionTime;
        @XmlElement(name = "Submission_Time", required = true)
        protected String submissionTime;
        @XmlElement(name = "Authorized_Time", required = true)
        protected String authorizedTime;
        @XmlElement(name = "TAT", required = true)
        protected String tat;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Procedure_Name", required = true)
        protected String procedureName;
        @XmlElement(name = "App_Amt")
        protected float appAmt;
        @XmlElement(name = "REMARKS", required = true)
        protected String remarks;

        /**
         * Gets the value of the refno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefno() {
            return refno;
        }

        /**
         * Sets the value of the refno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefno(String value) {
            this.refno = value;
        }

        /**
         * Gets the value of the patientName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientName() {
            return patientName;
        }

        /**
         * Sets the value of the patientName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientName(String value) {
            this.patientName = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the patientAge property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientAge() {
            return patientAge;
        }

        /**
         * Sets the value of the patientAge property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientAge(String value) {
            this.patientAge = value;
        }

        /**
         * Gets the value of the payerZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerZone() {
            return payerZone;
        }

        /**
         * Sets the value of the payerZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerZone(String value) {
            this.payerZone = value;
        }

        /**
         * Gets the value of the hospital property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospital() {
            return hospital;
        }

        /**
         * Sets the value of the hospital property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospital(String value) {
            this.hospital = value;
        }

        /**
         * Gets the value of the hospCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospCode() {
            return hospCode;
        }

        /**
         * Sets the value of the hospCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospCode(String value) {
            this.hospCode = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the memberCaste property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberCaste() {
            return memberCaste;
        }

        /**
         * Sets the value of the memberCaste property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberCaste(String value) {
            this.memberCaste = value;
        }

        /**
         * Gets the value of the cardNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardNo() {
            return cardNo;
        }

        /**
         * Sets the value of the cardNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardNo(String value) {
            this.cardNo = value;
        }

        /**
         * Gets the value of the patientTPAID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatientTPAID() {
            return patientTPAID;
        }

        /**
         * Sets the value of the patientTPAID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatientTPAID(String value) {
            this.patientTPAID = value;
        }

        /**
         * Gets the value of the firstSubmissionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstSubmissionTime() {
            return firstSubmissionTime;
        }

        /**
         * Sets the value of the firstSubmissionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstSubmissionTime(String value) {
            this.firstSubmissionTime = value;
        }

        /**
         * Gets the value of the submissionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmissionTime() {
            return submissionTime;
        }

        /**
         * Sets the value of the submissionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmissionTime(String value) {
            this.submissionTime = value;
        }

        /**
         * Gets the value of the authorizedTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizedTime() {
            return authorizedTime;
        }

        /**
         * Sets the value of the authorizedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizedTime(String value) {
            this.authorizedTime = value;
        }

        /**
         * Gets the value of the tat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAT() {
            return tat;
        }

        /**
         * Sets the value of the tat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAT(String value) {
            this.tat = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the procedureName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcedureName() {
            return procedureName;
        }

        /**
         * Sets the value of the procedureName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcedureName(String value) {
            this.procedureName = value;
        }

        /**
         * Gets the value of the appAmt property.
         * 
         */
        public float getAppAmt() {
            return appAmt;
        }

        /**
         * Sets the value of the appAmt property.
         * 
         */
        public void setAppAmt(float value) {
            this.appAmt = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREMARKS() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREMARKS(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HospCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Hospital" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PayerZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TDS" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="OtherDeduction" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="NetPayable" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="PaymentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ClaimProcessTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EftCreationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PaymentConfirmTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TAT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refNo",
        "hospCode",
        "hospital",
        "payerZone",
        "tds",
        "otherDeduction",
        "netPayable",
        "paymentStatus",
        "claimProcessTime",
        "eftCreationTime",
        "paymentConfirmTime",
        "tat"
    })
    public static class Shrdcpayment {

        @XmlElement(name = "RefNo", required = true)
        protected String refNo;
        @XmlElement(name = "HospCode", required = true)
        protected String hospCode;
        @XmlElement(name = "Hospital", required = true)
        protected String hospital;
        @XmlElement(name = "PayerZone", required = true)
        protected String payerZone;
        @XmlElement(name = "TDS")
        protected long tds;
        @XmlElement(name = "OtherDeduction")
        protected long otherDeduction;
        @XmlElement(name = "NetPayable")
        protected long netPayable;
        @XmlElement(name = "PaymentStatus", required = true)
        protected String paymentStatus;
        @XmlElement(name = "ClaimProcessTime", required = true)
        protected String claimProcessTime;
        @XmlElement(name = "EftCreationTime", required = true)
        protected String eftCreationTime;
        @XmlElement(name = "PaymentConfirmTime", required = true)
        protected String paymentConfirmTime;
        @XmlElement(name = "TAT", required = true)
        protected String tat;

        /**
         * Gets the value of the refNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefNo() {
            return refNo;
        }

        /**
         * Sets the value of the refNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefNo(String value) {
            this.refNo = value;
        }

        /**
         * Gets the value of the hospCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospCode() {
            return hospCode;
        }

        /**
         * Sets the value of the hospCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospCode(String value) {
            this.hospCode = value;
        }

        /**
         * Gets the value of the hospital property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHospital() {
            return hospital;
        }

        /**
         * Sets the value of the hospital property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHospital(String value) {
            this.hospital = value;
        }

        /**
         * Gets the value of the payerZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerZone() {
            return payerZone;
        }

        /**
         * Sets the value of the payerZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerZone(String value) {
            this.payerZone = value;
        }

        /**
         * Gets the value of the tds property.
         * 
         */
        public long getTDS() {
            return tds;
        }

        /**
         * Sets the value of the tds property.
         * 
         */
        public void setTDS(long value) {
            this.tds = value;
        }

        /**
         * Gets the value of the otherDeduction property.
         * 
         */
        public long getOtherDeduction() {
            return otherDeduction;
        }

        /**
         * Sets the value of the otherDeduction property.
         * 
         */
        public void setOtherDeduction(long value) {
            this.otherDeduction = value;
        }

        /**
         * Gets the value of the netPayable property.
         * 
         */
        public long getNetPayable() {
            return netPayable;
        }

        /**
         * Sets the value of the netPayable property.
         * 
         */
        public void setNetPayable(long value) {
            this.netPayable = value;
        }

        /**
         * Gets the value of the paymentStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentStatus() {
            return paymentStatus;
        }

        /**
         * Sets the value of the paymentStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentStatus(String value) {
            this.paymentStatus = value;
        }

        /**
         * Gets the value of the claimProcessTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClaimProcessTime() {
            return claimProcessTime;
        }

        /**
         * Sets the value of the claimProcessTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClaimProcessTime(String value) {
            this.claimProcessTime = value;
        }

        /**
         * Gets the value of the eftCreationTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEftCreationTime() {
            return eftCreationTime;
        }

        /**
         * Sets the value of the eftCreationTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEftCreationTime(String value) {
            this.eftCreationTime = value;
        }

        /**
         * Gets the value of the paymentConfirmTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentConfirmTime() {
            return paymentConfirmTime;
        }

        /**
         * Sets the value of the paymentConfirmTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentConfirmTime(String value) {
            this.paymentConfirmTime = value;
        }

        /**
         * Gets the value of the tat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAT() {
            return tat;
        }

        /**
         * Sets the value of the tat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAT(String value) {
            this.tat = value;
        }

    }

}
