
package gov.shdrc.webservice.cmchis.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceSHDRC", targetNamespace = "http://claim.cmchistn.com/SHDRC/", wsdlLocation = "http://claim.cmchistn.com/SHDRC/SHDRCWS.asmx?WSDL")
public class ServiceSHDRC
    extends Service
{

    private final static URL SERVICESHDRC_WSDL_LOCATION;
    private final static WebServiceException SERVICESHDRC_EXCEPTION;
    private final static QName SERVICESHDRC_QNAME = new QName("http://claim.cmchistn.com/SHDRC/", "ServiceSHDRC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://claim.cmchistn.com/SHDRC/SHDRCWS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESHDRC_WSDL_LOCATION = url;
        SERVICESHDRC_EXCEPTION = e;
    }

    public ServiceSHDRC() {
        super(__getWsdlLocation(), SERVICESHDRC_QNAME);
    }

    public ServiceSHDRC(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESHDRC_QNAME, features);
    }

    public ServiceSHDRC(URL wsdlLocation) {
        super(wsdlLocation, SERVICESHDRC_QNAME);
    }

    public ServiceSHDRC(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESHDRC_QNAME, features);
    }

    public ServiceSHDRC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSHDRC(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSHDRCSoap
     */
    @WebEndpoint(name = "ServiceSHDRCSoap")
    public ServiceSHDRCSoap getServiceSHDRCSoap() {
        return super.getPort(new QName("http://claim.cmchistn.com/SHDRC/", "ServiceSHDRCSoap"), ServiceSHDRCSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSHDRCSoap
     */
    @WebEndpoint(name = "ServiceSHDRCSoap")
    public ServiceSHDRCSoap getServiceSHDRCSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://claim.cmchistn.com/SHDRC/", "ServiceSHDRCSoap"), ServiceSHDRCSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESHDRC_EXCEPTION!= null) {
            throw SERVICESHDRC_EXCEPTION;
        }
        return SERVICESHDRC_WSDL_LOCATION;
    }

}
