
package gov.shdrc.webservice.cmchis.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSHDRCSoap", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSHDRCSoap {


    /**
     * 
     * @param recordDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PreauthDetails", action = "http://claim.cmchistn.com/SHDRC/PreauthDetails")
    @WebResult(name = "PreauthDetailsResult", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
    @RequestWrapper(localName = "PreauthDetails", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.PreauthDetails")
    @ResponseWrapper(localName = "PreauthDetailsResponse", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.PreauthDetailsResponse")
    public String preauthDetails(
        @WebParam(name = "Record_Date", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
        String recordDate);

    /**
     * 
     * @param recordDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ClaimsDetails", action = "http://claim.cmchistn.com/SHDRC/ClaimsDetails")
    @WebResult(name = "ClaimsDetailsResult", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
    @RequestWrapper(localName = "ClaimsDetails", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.ClaimsDetails")
    @ResponseWrapper(localName = "ClaimsDetailsResponse", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.ClaimsDetailsResponse")
    public String claimsDetails(
        @WebParam(name = "Record_Date", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
        String recordDate);

    /**
     * 
     * @param recordDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DcDetails", action = "http://claim.cmchistn.com/SHDRC/DcDetails")
    @WebResult(name = "DcDetailsResult", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
    @RequestWrapper(localName = "DcDetails", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.DcDetails")
    @ResponseWrapper(localName = "DcDetailsResponse", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.DcDetailsResponse")
    public String dcDetails(
        @WebParam(name = "Record_Date", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
        String recordDate);

    /**
     * 
     * @param recordDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PaymentDetails", action = "http://claim.cmchistn.com/SHDRC/PaymentDetails")
    @WebResult(name = "PaymentDetailsResult", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
    @RequestWrapper(localName = "PaymentDetails", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.PaymentDetails")
    @ResponseWrapper(localName = "PaymentDetailsResponse", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.PaymentDetailsResponse")
    public String paymentDetails(
        @WebParam(name = "Record_Date", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
        String recordDate);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HospitalDetails", action = "http://claim.cmchistn.com/SHDRC/HospitalDetails")
    @WebResult(name = "HospitalDetailsResult", targetNamespace = "http://claim.cmchistn.com/SHDRC/")
    @RequestWrapper(localName = "HospitalDetails", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.HospitalDetails")
    @ResponseWrapper(localName = "HospitalDetailsResponse", targetNamespace = "http://claim.cmchistn.com/SHDRC/", className = "shdrc.HospitalDetailsResponse")
    public String hospitalDetails();

}
